VirtualGlobalCollege/Controllers/StockBooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VirtualGlobalCollege.DAL;
using VirtualGlobalCollege.Models;

namespace VirtualGlobalCollege.Controllers
{
    public class StockBooksController : Controller
    {
        private SchoolContext db = new SchoolContext();

        // GET: StockBooks
        public ActionResult Index(string searchName)
        {
            var book = from m in db.StockBooks
                       select m;
            if (!String.IsNullOrEmpty(searchName))
            {
                book = book.Where(s => s.title.Contains(searchName));
            }


            return View(book);
        }

        // GET: StockBooks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StockBook stockBook = db.StockBooks.Find(id);
            if (stockBook == null)
            {
                return HttpNotFound();
            }
            return View(stockBook);
        }

        // GET: StockBooks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: StockBooks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,title,cost")] StockBook stockBook)
        {
            if (ModelState.IsValid)
            {
                db.StockBooks.Add(stockBook);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(stockBook);
        }

        // GET: StockBooks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StockBook stockBook = db.StockBooks.Find(id);
            if (stockBook == null)
            {
                return HttpNotFound();
            }
            return View(stockBook);
        }

        // POST: StockBooks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,title,cost")] StockBook stockBook)
        {
            if (ModelState.IsValid)
            {
                db.Entry(stockBook).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(stockBook);
        }

        // GET: StockBooks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StockBook stockBook = db.StockBooks.Find(id);
            if (stockBook == null)
            {
                return HttpNotFound();
            }
            return View(stockBook);
        }

        // POST: StockBooks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            StockBook stockBook = db.StockBooks.Find(id);
            db.StockBooks.Remove(stockBook);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VirtualGlobalCollege/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Virtual Global College</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Virtual Global Colege", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Students", "Index", "Students")</li>
                    <li>@Html.ActionLink("Courses", "Index", "Courses")</li>
                    <li>@Html.ActionLink("Books", "Index", "StockBooks")</li>
                    
                    


                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        

        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Virtual Global College</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>